### ISSUE TITLE
richiesta compatibilità plug-in wso2 con versioni APIM 

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [profesiait/weModI#1]
> Le librerie weModI sono compatibili con l'API Manager WSO2 versione 4.x

con tutte le versione di APIM?

- 4.0.0
- 4.1.0
- 4.2.0
- 4.3.0

**Comment by ggianoglio** [comment]
Le versioni compatibili sono:
* 4.1
* 4.2

Per la compatibilità con la 4.3 rilasceremo la versione 2.3 di weModI nelle prossime settimane.

**Comment by gianpaolo-tndigit** [comment]
grazie
